app = "openbiometrics-api"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  ENGINE_URL = "http://localhost:8000"
  DATABASE_URL = "sqlite+aiosqlite:////data/openbiometrics.db"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"

[mounts]
  source = "ob_data"
  destination = "/data"
